nelmio_api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui

#nelmio_api_doc:
 #   resource: '@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml'
 #   prefix: /api/doc

nelmio_api_doc_json:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger

#app.swagger:
    #path: /api/doc.json
    #controller: nelmio_api_doc.controller.swagger
