version: '3.8'

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: '!ChangeMe!'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: php -d variables_order=EGPCS -S 0.0.0.0:8000 -t public

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  postgres-data:
